// libs/ytc-front-angular/homepage/feature/src/lib/ytc-front-angular-homepage-feature.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SharedUiComponentsUiButtonComponent } from '@ytc/shared/ui-components/ui-button';
import { SharedUiComponentsUiBadgeComponent } from '@ytc/shared/ui-components/ui-badge';
import { SharedUiComponentsUiButtonBadgeComponent } from '@ytc/shared/ui-components/ui-button-badge';
import { SharedUiComponentsUiCardComponent } from '@ytc/shared/ui-components/ui-card';
import { SharedUiComponentsUiCardCenteredComponent } from '../../../../../shared/ui-components/ui-card-centered/src/lib/shared-ui-components-ui-card-centered.component';

@Component({
    selector: 'ytc-ytc-front-angular-homepage-feature',
    standalone: true,
    imports: [
        CommonModule,
        SharedUiComponentsUiButtonComponent,
        SharedUiComponentsUiBadgeComponent,
        SharedUiComponentsUiButtonBadgeComponent,
        SharedUiComponentsUiCardComponent,
        SharedUiComponentsUiCardCenteredComponent,
    ],
    templateUrl: './ytc-front-angular-homepage-feature.component.html',
})
export class YtcFrontAngularHomepageFeatureComponent {}

<p>ytc-front-angular-homepage-feature works!</p>
<div class="md:w-1/6 flex flex-col justify-center self-center mx-auto">
    <h1 class="text-2xl font-bold">{{ 'Welcome message' }}</h1>
    <!--    <InputTextMultiLabel-->
    <!--            topLeftLabel={t('homepage.labelInputApiKey')}-->
    <!--            placeholder={t('app.inputPlaceholder')}-->
    <!--            styleInput="input-primary"-->
    <!--            onInputChange={handleInputChange}-->
    <!--            defaultValue={import.meta.env.DEV && inputValue === '' ? import.meta.env.VITE_APP_API_KEY_MASTU : inputValue}-->
    <!--    />-->
    <!--    <Button buttonType="btn-primary" customStyle="w-fit" onClick={handleClick}>-->
    <!--        {t('app.login')}-->
    <!--    </Button>-->
</div>

// libs/ytc-front/homepage/feature/src/lib/ytc-front-homepage-feature.tsx
import { Button, InputTextMultiLabel } from '@ytc/shared/ui-components-react';
import { getUser } from '@ytc/shared/users/data-access';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { NavigateFunction, useNavigate } from 'react-router-dom';

export function YtcFrontHomepageFeature() {
    const { t } = useTranslation();
    const navigate: NavigateFunction = useNavigate();

    const [inputValue, setInputValue] = useState<string>('');

    const handleInputChange = (value: string) => {
        setInputValue(value);
    };

    const handleClick = (): void => {
        getUser(
            import.meta.env.DEV && inputValue === '' ? import.meta.env.VITE_APP_API_KEY_MASTU : inputValue,
        ).subscribe(user => {
            if (user) {
                navigate('channels', {
                    state: {
                        user,
                        apiKey:
                            import.meta.env.DEV && inputValue === ''
                                ? import.meta.env.VITE_APP_API_KEY_MASTU
                                : inputValue,
                    },
                });
            } else {
                console.log('No user found');
            }
        });
    };

    return (
        <div className="md:w-1/6 flex flex-col justify-center self-center mx-auto">
            <h1 className="text-2xl font-bold">{t('app.welcomeMsg')}</h1>
            <InputTextMultiLabel
                topLeftLabel={t('homepage.labelInputApiKey')}
                placeholder={t('app.inputPlaceholder')}
                styleInput="input-primary"
                onInputChange={handleInputChange}
                defaultValue={
                    import.meta.env.DEV && inputValue === '' ? import.meta.env.VITE_APP_API_KEY_MASTU : inputValue
                }
            />
            <Button buttonType="btn-primary" customStyle="w-fit" onClick={handleClick}>
                {t('app.login')}
            </Button>
        </div>
    );
}
